// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCofQb8zDhzxBP8kClkxnZMCfJPVr7Ie5o',
    appId: '1:64437760194:web:22b0d648d6cc12c2fd0b5b',
    messagingSenderId: '64437760194',
    projectId: 'soundmap-1ad52',
    authDomain: 'soundmap-1ad52.firebaseapp.com',
    storageBucket: 'soundmap-1ad52.firebasestorage.app',
    measurementId: 'G-KV2VME43XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT1JucTXmZYZ6vc4JNcWou0RBC5WeV5PI',
    appId: '1:64437760194:android:f815ea23f86284eefd0b5b',
    messagingSenderId: '64437760194',
    projectId: 'soundmap-1ad52',
    storageBucket: 'soundmap-1ad52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRS27pOLHf2fUtK0XJ619XGzLkvCeDac',
    appId: '1:64437760194:ios:5fb3e8171345a3a2fd0b5b',
    messagingSenderId: '64437760194',
    projectId: 'soundmap-1ad52',
    storageBucket: 'soundmap-1ad52.firebasestorage.app',
    iosBundleId: 'com.yourname.soundmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRS27pOLHf2fUtK0XJ619XGzLkvCeDac',
    appId: '1:64437760194:ios:5fb3e8171345a3a2fd0b5b',
    messagingSenderId: '64437760194',
    projectId: 'soundmap-1ad52',
    storageBucket: 'soundmap-1ad52.firebasestorage.app',
    iosBundleId: 'com.yourname.soundmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCofQb8zDhzxBP8kClkxnZMCfJPVr7Ie5o',
    appId: '1:64437760194:web:29f041e6940abf47fd0b5b',
    messagingSenderId: '64437760194',
    projectId: 'soundmap-1ad52',
    authDomain: 'soundmap-1ad52.firebaseapp.com',
    storageBucket: 'soundmap-1ad52.firebasestorage.app',
    measurementId: 'G-KSWXFTQRQ2',
  );
}
